### ISSUE TITLE
Docker containers in CI

### ISSUE THREAD

**Issue by c71n93** [CoolStory-Studio/coolstory-gram-client#6]
In terms of CI run efficiency it is better to use docker container with all installed dependencies.

Tasks:
- To create Dockerfiles for each OS and save these Dockerfiles in the `docker` folder
- To create docker images from this Dockerfiles.
- To create organization account on DockerHub and upload docker images.
- To make it possible to buid our project inside docker container.
- Edit github workflows so that it can build project inside this docker container.

@temikfart @cadnev WDYT?

**Comment by temikfart** [comment]
@c71n93 notice:
- docker image with installed dependecies must be uploaded on the Docker Hub on our organization account
- build project with Dockerfiles for each OS and save these Dockerfiles in the `docker` folder
- before editing CI yaml files, we need to make sure, that docker is installed on CI host machines.

Also, I think, that we can use only one runner, for example, ubuntu. Because we use docker.
